"""Workbook schema and controlled financial classifications."""

SHEETS = {
    "Properties": [
        "property_id",
        "name",
        "address",
        "property_type",
        "purchase_date",
        "purchase_price",
        "closing_costs",
        "initial_renovations",
        "down_payment",
        "other_initial_capital",
        "current_value",
        "annual_taxes",
        "annual_insurance",
        "annual_hoa",
        "expected_monthly_rent",
        "notes",
    ],
    "Units": ["unit_id", "property_id", "unit_name", "expected_monthly_rent", "notes"],
    "Loans": [
        "loan_id",
        "property_id",
        "original_principal",
        "origination_date",
        "interest_rate",
        "term_years",
        "amortization_years",
        "monthly_payment",
        "escrow_monthly",
        "current_balance",
        "balance_as_of",
        "notes",
    ],
    "Statements": [
        "statement_id",
        "period_start",
        "period_end",
        "original_filename",
        "local_filename",
        "sha256",
        "file_size",
        "imported_at",
        "revision",
        "status",
        "parser_version",
        "transaction_count",
        "validation_status",
        "message",
    ],
    "Property_Summaries": [
        "summary_id",
        "statement_id",
        "property_id",
        "property_name",
        "period_start",
        "period_end",
        "beginning_balance",
        "cash_in",
        "cash_out",
        "management_fees",
        "owner_disbursements",
        "ending_balance",
        "unpaid_bills",
        "property_reserve",
        "work_order_estimates",
        "net_owner_funds",
    ],
    "Transactions": [
        "transaction_id",
        "statement_id",
        "property_id",
        "property_name",
        "unit_id",
        "date",
        "payee_payer",
        "transaction_type",
        "reference",
        "description",
        "cash_in",
        "cash_out",
        "balance",
        "category",
        "financial_classification",
        "period_start",
        "period_end",
        "review_status",
    ],
    "External_Expenses": [
        "expense_id",
        "date",
        "property_id",
        "unit_id",
        "vendor",
        "description",
        "amount",
        "category",
        "financial_classification",
        "payment_method",
        "notes",
        "created_at",
        "source",
        "dedupe_key",
    ],
    "Property_Values": [
        "value_id",
        "property_id",
        "value_date",
        "estimated_value",
        "notes",
    ],
    "Loan_Adjustments": [
        "adjustment_id",
        "loan_id",
        "date",
        "amount",
        "adjustment_type",
        "notes",
    ],
    "Work_Orders": [
        "work_order_id",
        "statement_id",
        "property_id",
        "property_name",
        "work_order_number",
        "status",
        "created_on",
        "completed_on",
        "account",
        "amount",
        "over_limit",
    ],
    "Monthly_Metrics": [
        "period",
        "property_id",
        "property_name",
        "rental_income",
        "other_income",
        "operating_revenue",
        "operating_expenses",
        "noi",
        "capex",
        "mortgage_interest",
        "mortgage_principal",
        "debt_service",
        "cash_flow_after_debt",
        "expected_rent",
        "collection_rate",
        "expense_ratio",
        "dscr",
        "cap_rate_purchase",
        "cap_rate_current",
        "cash_on_cash",
        "estimated_equity",
        "ltv",
        "return_on_equity",
    ],
    "Import_Errors": [
        "error_id",
        "statement_id",
        "severity",
        "record_type",
        "record_key",
        "message",
        "original_value",
        "corrected_value",
        "status",
        "created_at",
    ],
    "Portfolio_Dashboard": ["metric", "value"],
    "Property_Dashboard": ["property_id", "property_name", "metric", "value"],
    "Lists": ["list_name", "value", "description"],
}

FINANCIAL_CLASSIFICATIONS = {
    "Maintenance / Operating Expense": "Included in operating expenses and reduces NOI.",
    "Capital Improvement / CapEx": "Excluded from NOI; reduces cash flow and increases invested capital.",
    "Mortgage Interest": "Excluded from NOI; included in debt service.",
    "Mortgage Principal": "Not an expense; reduces cash and loan balance.",
    "Owner Contribution": "Funding transfer; not income.",
    "Owner Distribution": "Owner transfer; not an expense.",
    "Property Acquisition Cost": "Capitalized into the property's investment basis.",
    "Sale Cost / Capital Gain": "Used only for a property sale.",
}

OPERATING_CLASSIFICATIONS = {"Maintenance / Operating Expense"}
TRANSFER_CLASSIFICATIONS = {"Owner Contribution", "Owner Distribution"}
